[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "dotnet Colportor.Api.dll"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
