-- Migration para adicionar apenas as tabelas do WhatsApp
-- Executar manualmente no banco de dados

-- Tabela WhatsAppConnections
CREATE TABLE "WhatsAppConnections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhoneNumber" character varying(20) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "LastConnection" timestamp with time zone,
    "LastDisconnection" timestamp with time zone,
    "QrCode" character varying(500),
    "QrCodeGeneratedAt" timestamp with time zone,
    "QrCodeExpiresAt" timestamp with time zone,
    "ErrorMessage" character varying(1000),
    "SessionData" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedByUserId" integer NOT NULL,
    CONSTRAINT "PK_WhatsAppConnections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WhatsAppConnections_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Tabela WhatsAppMessages
CREATE TABLE "WhatsAppMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MissionContactId" integer NOT NULL,
    "Content" character varying(1000) NOT NULL,
    "Sender" character varying(50) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "MediaUrl" character varying(500),
    "MediaType" character varying(50),
    "WhatsAppMessageId" character varying(100),
    "SentByUserId" integer,
    CONSTRAINT "PK_WhatsAppMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WhatsAppMessages_MissionContacts_MissionContactId" FOREIGN KEY ("MissionContactId") REFERENCES "MissionContacts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WhatsAppMessages_Users_SentByUserId" FOREIGN KEY ("SentByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

-- Tabela WhatsAppTemplates
CREATE TABLE "WhatsAppTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Content" character varying(1000) NOT NULL,
    "Category" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedByUserId" integer NOT NULL,
    "AvailableVariables" character varying(500),
    CONSTRAINT "PK_WhatsAppTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WhatsAppTemplates_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Índices para WhatsAppConnections
CREATE INDEX "IX_WhatsAppConnections_CreatedAt" ON "WhatsAppConnections" ("CreatedAt");
CREATE INDEX "IX_WhatsAppConnections_CreatedByUserId" ON "WhatsAppConnections" ("CreatedByUserId");
CREATE INDEX "IX_WhatsAppConnections_PhoneNumber" ON "WhatsAppConnections" ("PhoneNumber");
CREATE INDEX "IX_WhatsAppConnections_Status" ON "WhatsAppConnections" ("Status");

-- Índices para WhatsAppMessages
CREATE INDEX "IX_WhatsAppMessages_MissionContactId" ON "WhatsAppMessages" ("MissionContactId");
CREATE INDEX "IX_WhatsAppMessages_SentByUserId" ON "WhatsAppMessages" ("SentByUserId");
CREATE INDEX "IX_WhatsAppMessages_Status" ON "WhatsAppMessages" ("Status");
CREATE INDEX "IX_WhatsAppMessages_Timestamp" ON "WhatsAppMessages" ("Timestamp");

-- Índices para WhatsAppTemplates
CREATE INDEX "IX_WhatsAppTemplates_Category" ON "WhatsAppTemplates" ("Category");
CREATE INDEX "IX_WhatsAppTemplates_CreatedAt" ON "WhatsAppTemplates" ("CreatedAt");
CREATE INDEX "IX_WhatsAppTemplates_CreatedByUserId" ON "WhatsAppTemplates" ("CreatedByUserId");
CREATE INDEX "IX_WhatsAppTemplates_IsActive" ON "WhatsAppTemplates" ("IsActive");

